### ISSUE TITLE
How to provide styling to tooltip. 

### ISSUE THREAD

**Issue by xinhash** [netzwerg/react-svg-tooltip#9]
For my use case I have to provide tooltip on an svg element at corner of the screen. The tooltip overflows from the screen which is weird. How to prevent this
![image](https://thumb.ibb.co/dPty6p/Screen_Shot_2018_09_26_at_5_59_52_PM.png)

**Comment by netzwerg** [comment]
Apologies for not answering earlier, somehow GitHub did not notify me about this issue.

You can adjust the positioning of the tooltip by enclosing the contents in a `g`, which you then transform accordingly:

```jsx
<Tooltip triggerRef={circleRef}>
  <g transform="translate(-10,0)">
    <rect x={2} y={2} width={10} height={5} rx={.5} ry={.5} fill='black'/>
    <text x={5} y={5} fontSize={2} fill='white'>Yay!</text>
  </g>
</Tooltip>
``` 
The actual transformation depends on how big your tooltip actually is, and whether you're hitting the top/right/bottom/left browser window edge. The library cannot do this for you (because it does not know how big your tooltip actually is). However, @benjaminrosenbaum wanted to provide helper methods at one point – is this still on your agenda, Ben?
